### ISSUE TITLE
Problemas de redireccionamiento

### ISSUE THREAD

**Issue by IngrownMink4** [gitatmanu/estadodelmce#1]
Hola buenas!

Quería comentar que hay un mal redireccionamiento en algunos partidos comunistas de la lista. En vez de dirigirse a la página web del partido, aparece el mensaje “Not Found” esto supongo que ocurre porque en vez de redirigir a la página web original (por ejemplo, la de [independenciaobrera.org](independenciaobrera.org)), se redirige a `https://estadodelmce.es/lista-de-partidos/`

![firefox_kHBvx8EBu9](https://user-images.githubusercontent.com/25466522/127745118-070a6dbf-512d-415b-a307-475d2dbf5b25.png)

**Esto ocurre en las siguientes páginas:**
- GIO - GRUPO INDEPENDENCIA OBRERA (https://estadodelmce.es/lista-de-partidos/independenciaobrera.org)
- CCI - CORRIENTE COMUNISTA INTERNACIONAL (https://estadodelmce.es/lista-de-partidos/es.internationalism.org)
- CRIDA COMUNISTA (https://estadodelmce.es/lista-de-partidos/cridacomunista.org)
- HERRI GORRI (https://estadodelmce.es/lista-de-partidos/herrigorri.com)
- UPG - UNION DO POVO GALEGO (https://estadodelmce.es/lista-de-partidos/upg.gal)

Si se quita la parte de `https://estadodelmce.es/lista-de-partidos/`, se soluciona el problema.

**Comment by gitatmanu** [comment]
Gracias por el aviso! Lo tenía en cuenta, pero me daba pereza ir uno por uno poniendo bien la URL.
